### PR TITLE
Fixed RegEx

### PR DESCRIPTION
**Pull request by ItsJordan**

### CODE REVIEW

**Comment by TeeSeal** [comment]
Quality PR's, as usual

**Comment by ItsJordan** [comment]
You know it 💯 🥇

**Comment by kurisubrooks** [comment]
Looks fine to me?? ¯\_(ツ)_/¯

**Comment by ItsJordan** [comment]
Hi kuri <3

**Comment by kurisubrooks** [comment]
Yes hello, let us not pollute GitHub with our spam.

**Pull request merged**
