### PR TITLE
Better RegEx for invites

### PR DESCRIPTION
**Pull request by ItsJordan**

### CODE REVIEW

**Comment by KyeNormanGill** [comment]
I'm not entirely sure how regexs work but invite links have /gg in them and i don't see it in there

**Comment by KyeNormanGill** [comment]
nvm i'm blind

**Comment by kurisubrooks** [comment]
@KyeNormanGill pls
screenshot 2017-03-04 03 26 29

**Comment by alucard0134** [comment]
iconic

**Pull request merged**
